### ISSUE TITLE
Tuya Zigbee Curtain Module requires open/close time calibration 

### ISSUE THREAD

**Issue by Capetrip** [JohanBendz/com.tuya.zigbee#257]
Hello Johan, 

I purchased a Tuya Zigbee Curtain Device (MOES) as per below:
https://www.amazon.de/dp/B091CZ4L4W?ref=ppx_yo2ov_dt_b_product_details&th=1

Unfortunately it adds into Homey only as a Generic Zigbee Device and not as a Curtain Module. Thus I am unable to control the roller shutter.

Any idea how to get it added as a Curtain Device? 
My Homey is Homey (Early 2019). The App Version is V01.45

Any help appreciated !

Regards,
Uli

**Comment by Capetrip** [comment]
Forgot to provide my Manufacturer and Product ID from the Tuya Device:
_TZ3000_1dd0d5yi / TS130F

**Comment by Capetrip** [comment]
Solved the issue. The curtain module has been added now fine in the test version of the App. However the it opens / closes only 2/3 as the open / close times are fixed and there seems to be no calibration. 
Can calibration been added ? Would that be possible or alternatively provide a indefinite open / close command and let the motor open/close till it stops automatically.

**Comment by Majebo** [comment]
Hi @Capetrip did u fix your problem yet? I posted the exact same problem on this Github. But still no respons nor fix. If u do have a fix please let me know.

**Comment by Capetrip** [comment]
Hi Johan. No I returned the Tuya devices and got other brands which work well. 


_______________
Sent via iPhone

**Comment by Torpen29** [comment]
Hi Capetrip.
You spoke about "other brands", could you say please which are these brands ?
Thanks

**Comment by Capetrip** [comment]
Hi,
Yes I bought the Qubino flush shutter. Different price point but works well also with Homey integration. 

Regards,
Uli 


_______________
Sent via iPhone

**Comment by Torpen29** [comment]
Thanks a lot for your answer.

I already tested it but it didn't work in my essentially zigbee configuration,
too far from my homey

Pierre




Le 08/03/2023 à 01:03, Capetrip ***@***.***> écrit :


Hi,
Yes I bought the Qubino flush shutter. Different price point but works well
also with Homey integration.

Regards,
Uli


_______________
Sent via iPhone

> Am 07.03.2023 um 16:27 schrieb Torpen29 ***@***.***>:
>
> ﻿
> Hi Capetrip.
> You spoke about "other brands", could you say please which are these brands
?
> Thanks
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID:
***@***.***>


-- 
Cet e-mail a été vérifié par le logiciel antivirus d'Avast.
www.avast.com

**Comment by schorsch** [comment]
After adding the device it took a few seconds until the device was fully detected in the UI. The default engine runtime is 10 seconds. Since the motors should have calibrated endpoints, one has to increase the runtime and should be save.
I only have to figure out the open/close percentage, because it does not seem to match the chosen value in the UI.

**Comment by JohanBendz** [comment]
Device now have calibration functionality
